#ifndef PLAYERROR_H
#define PLAYERROR_H

	#define PLAY_CLOSE_AVI_FAILED			-17
	#define PLAY_SAVE_AVI_FAILED			-16
	#define PLAY_OPEN_AVI_NEED_SYSTEM_FRAME	-15
	#define PLAY_OPEN_AVI_FAILED			-14
	#define PLAY_CONVERT_AUDIO_FAILED		-13
	#define PLAY_GET_SNAPSHOT_SIZE_SMALL	-12
	#define PLAY_GET_SNAPSHOT_FAILED		-11
	#define PLAY_SAVEAVI_FAILED				-10
	#define PLAY_PUSH_FRAME_NOT_I			-9
	#define PLAY_SAVEAVI_BEGIN_ER			-8
	#define PLAY_GET_DECODE_TYPE_ER			-7
	#define PLAY_GET_DECODE_EMPTY			-6
	#define PLAY_NOT_PLAY_AUDIO				-5
	#define PLAY_GET_DECODE_FAIL			-4
	#define PLAY_BUFFER_IS_FULL				-3
	#define PLAY_PUSH_FRAME_FAILED			-2
	#define PLAY_CHANNEL_ER					-1

	#define PLAY_PUSH_FRAME_SUCCESS			0

	#define PLAY_SET_BUFFER_SIZE_SUCCESS	1
	#define PLAY_SET_WINDOW_SIZE_SUCCESS	2
	#define PLAY_GET_MPEG4_SUCCESS			3
	#define PLAY_SET_PLAY_AUDIO_SUCCESS		4
	#define PLAY_SNAPSHOT_SUCCESS			5
	#define PLAY_GETPLAYTIME_SUCCESS		6
	#define PLAY_GET_DECODE_SUCCESS			7
	#define PLAY_SAVEAVI_SUCCESS			8
	#define PLAY_SET_PLAY_IONLY_SUCCESS		9
	#define PLAY_SET_HANDLE_SUCCESS			10
	#define PLAY_CONVERT_AUDIO_SUCCESS		11
	#define PLAY_SET_VIDEO_FLIP_SUCCESS		12
	#define PLAY_SET_VIDEO_MIRROR_SUCCESS	13
	#define PLAY_OPEN_AVI_SUCCESS			14
	#define PLAY_CLOSE_AVI_SUCCESS			15
	#define PLAY_SAVE_AVI_SUCCESS			16
	#define PLAY_SET_OSD_SUCCESS			17
#endif